In [ ]:
import numpy as np

#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [13]:
a =np.random.random((4,4))
print(a)

[[0.40683946 0.55496891 0.98623304 0.66435675]
 [0.85257955 0.08954311 0.68022368 0.79640898]
 [0.63322991 0.33998543 0.205293   0.33206592]
 [0.64546996 0.85306125 0.60875135 0.72849781]]


#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
a= np.random.randint(1,11,(5,5))
print(a)

[[10  9  7  5  3]
 [ 6  8  5  6  6]
 [ 7  4  3  4  1]
 [ 6  3  4  9  2]
 [ 1  1  2  9 10]]


#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [4]:
a=np.zeros((3,3))
print(a)
b=np.full((3,3),0)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [ ]:

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
