In [4]:
import numpy as np

#1.Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [6]:

a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


#2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [5]:
a=np.zeros((3,3))
print(a)
b=np.full((3,3),0)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


#3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
a= np.random.randint(1,11,(5,5))
print(a)

[[ 9  7  4  4 10]
 [ 5  7  9  9  8]
 [ 6  1  3 10 10]
 [ 5  5  8  6 10]
 [ 3  3  8  1  6]]


#4.Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [8]:
a =np.random.random((4,4))
print(a)

[[0.47863492 0.99499389 0.42182712 0.65148643]
 [0.51219523 0.82388342 0.44705817 0.47529704]
 [0.40399842 0.02345838 0.70553931 0.93625902]
 [0.13491986 0.5823494  0.0969226  0.43579375]]


#5.Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [9]:
a= np.random.randint(1,11,(5,))
b= np.random.randint(1,11,(5,))
print(a+b)
print(a-b)
print(a*b)

[11 17 16 10 13]
[ 3 -1  4  6  7]
[28 72 60 16 30]


#6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [18]:
a= np.random.random(7)
b= np.random.random(7)
print(np.dot(a,b))

2.5897083756892454


#7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [21]:
a= np.random.randint(1,11,(2,2))
b= np.random.randint(1,11,(2,3))
print(np.dot(a,b))

[[ 98 125  75]
 [108 135  81]]


#8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [25]:
a= np.random.randint(1,11,(3,3))
inv_a = np.linalg.inv(a)
print(inv_a)

[[-0.0617284  -0.12345679  0.2345679 ]
 [-0.2037037   0.09259259  0.07407407]
 [ 0.31481481  0.12962963 -0.2962963 ]]


#9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [26]:
a=np.random.random((4,4))
print(a.T)

[[0.36455352 0.16304697 0.56018346 0.46616249]
 [0.3978663  0.99047518 0.54328652 0.71077685]
 [0.91562561 0.83856461 0.11512175 0.14588882]
 [0.45476445 0.3572815  0.13458802 0.33598207]]


#10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [27]:
a=np.random.randint(1,11,(3,4))
b=np.random.randint(1,11,(4,))
print(np.dot(a,b))

[173 217 236]


#11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [30]:
a=np.random.random((2,3))
b=np.random.random(3)
print(np.dot(a,b))

[0.55102985 0.70325183]


#12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [32]:
a=np.random.randint(1,11,(2,2))
b=np.random.randint(1,11,(2,2))
print(a*b)

[[ 6 35]
 [49 40]]


#13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [34]:
a=np.random.randint(1,11,(2,2))
b=np.random.randint(1,11,(2,2))
print(np.dot(a,b))

[[20 42]
 [68 79]]


#14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [35]:
a=np.random.randint(1,101,(5,5))
print(np.sum(a))


1207


#15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [36]:
a=np.random.randint(1,11,(4,4))
b=np.random.randint(1,11,(4,4))
print(a-b)

[[ 2 -6  6 -7]
 [ 9  3  0  1]
 [ 3  1 -4 -1]
 [-3  1  0  6]]


#16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [41]:
a= np.random.randint(1,11,(3,3))

print(np.sum(a, axis=1).reshape(-1,1))

[[19]
 [13]
 [10]]


#17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [42]:
a= np.random.randint(1,11,(3,4))
b= a**2
print(b)

[[ 9 49  1 25]
 [36  1 16  1]
 [64 25 49  4]]


#18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел

In [43]:
a=np.random.randint(1,51,(4))
print(np.sqrt(a))

[6.92820323 4.35889894 7.07106781 6.4807407 ]
